name: publish npm

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
              pwd
              echo "//registry.npmjs.org/:_authToken=${PERSONAL_ACCESS_TOKEN}" > .npmrc
              ls -la
              echo "${PERSONAL_ACCESS_TOKEN}"
              npm install

      # - name: Publish to npm
      #   env:
      #     NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
      #     NPM_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      #     GITHUB_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      #   run: npm publish --access public
        